"""Shared database helpers, logging, and schema validation for data-engineering scripts."""
import logging
import os
import sys
from pathlib import Path

from sqlalchemy import create_engine, text

from config import DATABASE_URL, ANALYTICS_DATABASE_URL

_engine = None
_analytics_engine = None

# Log files go into data-engineering/logs/<script_name>.log
LOGS_DIR = Path(__file__).parent / "logs"


def setup_logging(name: str) -> logging.Logger:
    """Return a logger that writes to both stdout and logs/<name>.log."""
    logger = logging.getLogger(name)
    if not logger.handlers:
        fmt = logging.Formatter(
            "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
        )

        # Console handler
        console = logging.StreamHandler(sys.stdout)
        console.setFormatter(fmt)
        logger.addHandler(console)

        # File handler — one file per script in logs/
        LOGS_DIR.mkdir(exist_ok=True)
        # Use the last part of the dotted module name as the filename
        log_filename = name.rsplit(".", 1)[-1] if "." in name else name
        file_handler = logging.FileHandler(
            LOGS_DIR / f"{log_filename}.log", encoding="utf-8"
        )
        file_handler.setFormatter(fmt)
        logger.addHandler(file_handler)

        logger.setLevel(logging.INFO)
    return logger


def get_engine():
    """Return a singleton SQLAlchemy engine for the source database."""
    global _engine
    if _engine is None:
        _engine = create_engine(DATABASE_URL, pool_pre_ping=True)
    return _engine


def get_analytics_engine():
    """Return a singleton SQLAlchemy engine for the analytics database."""
    global _analytics_engine
    if _analytics_engine is None:
        _analytics_engine = create_engine(ANALYTICS_DATABASE_URL, pool_pre_ping=True)
    return _analytics_engine


# ---------------------------------------------------------------------------
# Expected schema — single source of truth for table/column validation
# ---------------------------------------------------------------------------
EXPECTED_SCHEMA = {
    "users": {
        "ddl": """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email VARCHAR(255) NOT NULL UNIQUE,
                name VARCHAR(255) NOT NULL,
                password VARCHAR(255) NOT NULL,
                role VARCHAR(20) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                is_active BOOLEAN DEFAULT TRUE
            )
        """,
        "columns": {"id", "email", "name", "password", "role", "created_at", "is_active"},
    },
    "categories": {
        "ddl": """
            CREATE TABLE IF NOT EXISTS categories (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL UNIQUE,
                description VARCHAR(255)
            )
        """,
        "columns": {"id", "name", "description"},
    },
    "posts": {
        "ddl": """
            CREATE TABLE IF NOT EXISTS posts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                content TEXT NOT NULL,
                category_id BIGINT,
                author_id BIGINT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                is_deleted BOOLEAN DEFAULT FALSE,
                CONSTRAINT fk_post_category FOREIGN KEY (category_id) REFERENCES categories(id),
                CONSTRAINT fk_post_author FOREIGN KEY (author_id) REFERENCES users(id)
            )
        """,
        "columns": {
            "id", "title", "content", "category_id", "author_id",
            "created_at", "updated_at", "is_deleted",
        },
    },
    "comments": {
        "ddl": """
            CREATE TABLE IF NOT EXISTS comments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                content TEXT NOT NULL,
                post_id BIGINT NOT NULL,
                author_id BIGINT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                is_deleted BOOLEAN DEFAULT FALSE,
                CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES posts(id),
                CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users(id)
            )
        """,
        "columns": {"id", "content", "post_id", "author_id", "created_at", "is_deleted"},
    },
}


def ensure_schema(conn, logger=None):
    """Create tables if missing; log column mismatches for existing tables.

    Call this before any seed or ETL work to guarantee the schema is ready.
    Tables are created with IF NOT EXISTS so this is safe to run repeatedly.
    """
    _log = logger or logging.getLogger(__name__)

    for table_name, spec in EXPECTED_SCHEMA.items():
        # Check if table exists
        exists = conn.execute(text(
            "SELECT EXISTS ("
            "  SELECT 1 FROM information_schema.tables "
            "  WHERE table_schema = 'public' AND table_name = :t"
            ")"
        ), {"t": table_name}).scalar()

        if not exists:
            _log.warning("Table '%s' does not exist — creating it now", table_name)
            conn.execute(text(spec["ddl"]))
            conn.commit()
            _log.info("Table '%s' created successfully", table_name)
        else:
            # Table exists — verify columns match expectations
            rows = conn.execute(text(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema = 'public' AND table_name = :t"
            ), {"t": table_name}).fetchall()
            actual_columns = {row[0] for row in rows}
            expected_columns = spec["columns"]

            missing = expected_columns - actual_columns
            extra = actual_columns - expected_columns

            if missing:
                _log.warning(
                    "Table '%s' is MISSING expected columns: %s",
                    table_name, ", ".join(sorted(missing)),
                )
            if extra:
                _log.info(
                    "Table '%s' has extra columns (added by backend?): %s",
                    table_name, ", ".join(sorted(extra)),
                )
            if not missing and not extra:
                _log.info("Table '%s' schema OK (%d columns)", table_name, len(actual_columns))
